### PR TITLE
Fix project name in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by cgruber** [comment]
Test. The CLAbot seems to not be working. :/

**Comment by cgruber** [comment]
Test

**Comment by cgruber** [comment]
Sorry to ask, but can you please sign the CLA here: https://cla.developers.google.com/clas  I can't find you in our CLA database.

**Comment by fbiville** [comment]
Héhé, OK. I didn't know this kind of change would require signing the CLA :)

**Comment by fbiville** [comment]
CLA is now submitted :)

**Pull request merged**
