### PR TITLE
Add withDiagnosticContaining to compilations

### PR DESCRIPTION
**Pull request by guicamest**
Add withDiagnosticContaining to both Unsuccessful and Successful compilations

### CODE REVIEW

**Comment by guicamest** [comment]
I signed it!

**Comment by guicamest** [comment]
@cgruber  @gk5885 Did you have time to take a look at this?

**Comment by smsiebe** [comment]
would love to see this merged!

**Comment by cgruber** [comment]
Ok.  Starting to review this.

**Comment by cgruber** [comment]
Sorry - we had to release an interim release and I have been working on six high-priority things at once.  I won't get to this for a bit (e.g. next week probably, when I'll look at c-t more broadly), but it might be obsolete, as we're looking at a different way to structure this, which I"ll be writing up, that will effect the same change, more or less.

I will leave this open for now.

**Comment by gk5885** [comment]
I am terribly sorry that this p/r languished for so long.  @netdpb is working on adding this feature with a slightly different API.  We're also addressing the issue that most developers will probably forget that they'd need `.withCompilerOptions("-Xlint:all")` in order for most warnings to actually show up.

So, I'm going to close this for now, but we should have the functionality soon.

**Comment by sameb** [comment]
FYI, you may want to look at error-prone's CompilationTestHelper (https://github.com/google/error-prone/blob/master/core/src/test/java/com/google/errorprone/CompilationTestHelper.java) & DiagnosticTestHelper (https://github.com/google/error-prone/blob/master/core/src/test/java/com/google/errorprone/DiagnosticTestHelper.java) for inspiration.   They follow a pattern of putting comments in the tested source code to signal where you want the error to be (so that you don't need to worry about row/col numbers, but can still target things), and I recently updated it to allow using arbitrary Predicates to programatically check the diagnostic msg.

**Comment by gk5885** [comment]
Yeah, that's pretty nifty.  Generally error-prone gets away with a lot more than we can because they have access to the full AST, but a quick glance suggests that it _might_ only rely on `javax.tools`.  If that's the case, I'd _love_ to consolidate.

**Pull request closed without merging**
