### PR TITLE
Add an ability to pass in compiler configuration options

### PR DESCRIPTION
**Pull request by cgruber**
Add an ability to pass in compiler configuration options (say, to configure annotation processors' flags).

-------------
Created by MOE: http://code.google.com/p/moe-java
MOE_MIGRATED_REVID=85151739

### CODE REVIEW

**Comment by gk5885** [comment]
LGTM

**Comment by velo** [comment]
Any idea when will it be released?

**Comment by cgruber** [comment]
I'll roll a release this week.

**Comment by velo** [comment]
great!

**Comment by liptga** [comment]
Can someone tell me how to use the options in a test? I cannot find any example in the javadoc and it seems to me not trivial to pass the options into com.google.testing.compile.Compilation.compile(Iterable<? extends Processor>, Set<String>, Iterable<? extends JavaFileObject>)

**Comment by liptga** [comment]
Ok, I figured it out. Example:
```java
		assert_().about(javaSource()).that(JavaFileObjects.forSourceString(
				"foo.HelloWorld", 
				"package foo;"
				+ "@xxxx.Persistable\n"
				+ "final class HelloWorld {}")).withCompilerOptions("-AprocessorParameterExample=bar").processedWith( new Processor() ).compilesWithoutError();
```

**Pull request merged**
