### PR TITLE
stop casting the compiler to JavacTool

### PR DESCRIPTION
**Pull request by h908714124**
* JavacTool is missing in JDK 9
* cast the task to JavacTask instead

### CODE REVIEW

**Comment by h908714124** [comment]
Thanks google, but I'm not signing anything.

**Comment by h908714124** [comment]
[Here](http://www.docjar.com/html/api/com/sun/tools/javac/api/JavacTool.java.html), it says:

> This is NOT part of any supported API.
> If you write code that depends on this, you do so at your own
> risk.  This code and its internal interfaces are subject to change
> or deletion without notice.

**Comment by ronshapiro** [comment]
Good catch - this cast appears to be totally unnecessary.

Unfortunately we can't accept any patches that are not accompanied with a CLA.

**Comment by h908714124** [comment]
I'd rather stay anonymous

**Comment by ronshapiro** [comment]
In that case, we'll have to reject this contribution, sorry.

**Comment by ronshapiro** [comment]
I haven't been able to reproduce this issue. Do you mind filing a separate issue with your setup and what you're seeing?

Perhaps this is an issue with not including the right modules (`jdk.compiler`)? I'm seeing that type in java 9

**Pull request closed without merging**
