### PR TITLE
Provide ClassLoader for loading generated classes and resources

### PR DESCRIPTION
**Pull request by dnault**
Add `Compilation.classLoader()` method (and an overloaded version that takes a parent classloader). The returned ClassLoader is useful for loading generated classes and resources.

### CODE REVIEW

**Comment by dnault** [comment]
I signed it!

**Comment by dnault** [comment]
Ping, I signed the CLA.

**Comment by netdpb** [comment]
Thanks! We're going to bring this to our API review meeting.

**Comment by netdpb** [comment]
@dnault, what are some examples of use cases where you'd use either loading the class or the resources? What's the advantage of using Compile-Testing at runtime and not simply building the class itself at build time?

Are there dangers in trying to load a class that might have been compiled with, for instance, -source 7 target 7 -bootclasspath $JDK7/lib/rt.jar into a test that's running with JDK8?

**Comment by dnault** [comment]
Hi @netdpb , thanks for taking a look at this.

It's useful for writing unit tests that check the behavior of classes generated by annotation processors.

As a concrete example, the therapi-runtime-javadoc project uses an annotation processor to generate buddy classes. Each buddy class has a static method which returns the Javadoc from the original class. The requirement is to check whether the generated class actually returns the correct Javadoc. If you're curious, the test code is here:

https://github.com/dnault/therapi-runtime-javadoc/blob/master/src/test/java/com/github/therapi/runtimejavadoc/JavadocAnnotationProcessorTest.java

(This example does not rely on using a class loader to load resources, but you can imagine a generated class might want to load generated resources.)

The advantage of using Compile-Testing at test runtime is that it does not require any build process shenanigans. An alternative would be to create a separate project just for testing, an approach that was not considered attractive.

Another alternative would be to compare the generated buddy sources against a set of golden files, but that's less desirable since we care about testing the *behavior* of the buddy class and how it interacts with the rest of the library, not the implementation details.

Regarding cross-compilation, specifying the boot class path ensures the compilation will fail if the code references classes not present in the target version, so that's not a problem. That said, a class compiled for JDK7 will fail to run in JDK8 if it relies on an API that was removed in JDK8, but that's always an issue no matter how the code is executed. Apart from that, I'm not aware of any pitfalls.

Cheers,
David

**Comment by netdpb** [comment]
I'm not sure about "a separate project". For example, Dagger has functional tests, where classes actually get built using Dagger and then the tests actually use the class. See https://github.com/google/dagger/tree/master/javatests/dagger/functional for the code there.

In what way would adding class/resource loading to compile-testing be a better alternative to a functional-test approach like that one?

**Comment by dnault** [comment]
@netdb You are correct, it is possible to do functional testing by simply putting the annotated class in the test path. However it requires a bit of IDE configuration to make this happen in IntelliJ.

In my case, the solution was enabling the "Delegate IDE build/run actions to gradle" option. This setting is found under "Build, Execution, Deployment > Build Tools > Gradle > Runner". Not ideal, but tolerable.

Looks like this isn't the first time such a feature was proposed: #70 "Compile generated code and execute it".

**Comment by netdpb** [comment]
OK. I think that's an acceptable path to getting what you need that doesn't mean adding features to Compile-Testing. I'm going to close this issue for now. Please feel free to reopen it if you think of other reasons or arguments for it.

Thanks!

**Pull request closed without merging**
