### PR TITLE
Merge changes from google.

### PR DESCRIPTION
**Pull request by cgruber**
Quite a few changes, as it's been a while.  Including:

  * More lenient treatment of equality between different JavaFileObject implementations
  * Better error messages in some cases
  * Proposition to check that a generated file contains a string
  * Proposition(s) to permit assertions about warnings and notes.
  * Other minor stuff.

### CODE REVIEW

**Comment by cgruber** [comment]
Note - I cancelled the second build.  It's superfluous.

**Comment by gk5885** [comment]
Looks like you have some travis issues…

**Comment by cgruber** [comment]
AS I said before, I manually cancelled that, since it was running the same build twice.  Travis is good.

**Comment by cgruber** [comment]
FWIW, it was me trying to ease our load on our travis bots.  I'll be sending out cleanup CLs to whitelist "master" as the only non-pull-request based thing to invoke a travis build.

**Comment by gk5885** [comment]
LGTM

**Pull request merged**
